### ISSUE TITLE
Error doing update on Dcard

### ISSUE THREAD

**Issue by pm5** [disinfoRG/ZeroScraper#83]
Found an error in [cronjob logs](https://middle2.com/project/downloadcronlog/tainan-sun-500796/2020-03-02T10:56:49+08:00/172/stderr):

```
Traceback (most recent call last):
  File "./ns.py", line 124, in <module>
    main(args)
  File "./ns.py", line 96, in main
    update(args)
  File "./ns.py", line 80, in update
    newsSpiders.runner.update.run(runner, site["site_id"])
  File "/srv/web/newsSpiders/runner/update.py", line 67, in run
    site_id=site_id, current_time=current_time
  File "/srv/web/newsSpiders/runner/update.py", line 31, in get_posts_to_update
    for post in posts
  File "/srv/web/newsSpiders/runner/update.py", line 31, in <listcomp>
    for post in posts
  File "/srv/web/newsSpiders/runner/update.py", line 18, in get_last_comment_floor
    )["raw_data"]
TypeError: 'NoneType' object is not subscriptable
```

Looks like a problem getting the lastest floor of Dcard comments.  This happens during the creation of spiders so an uncaught exception here will abort updates for all sites.

**Comment by pm5** [comment]
Note: we have backup up to 2/17.  Working on data recovery 2/17-2/28
